#!/usr/bin/env python3
"""
Simplified Trust-Based Sensor Fusion Algorithm

Simplified version using:
- Current-time detections only (no historical tracks)
- Direct object ID matching, walked from each ego robot's OWN reported tracks (no
  Hungarian assignment, no position-based fusion). PSMs are generated by asking, for
  each of ego's own tracks, whether proximal robots corroborate it - not the other way
  around - so an object only a proximal robot fabricates never generates a PSM for
  ego robots that correctly never reported it.

Based on: "Trust-Based Assured Sensor Fusion in Distributed Aerial Autonomy"
"""

import numpy as np
from typing import List, Dict, Tuple
from trust_algorithm import TrustAlgorithm
from robot_track_classes import Robot, Track


class TrustEstimator:
    """Implements the original paper's trust estimation using assignment-based PSM generation"""
    
    def __init__(self, negative_bias: float = 10.0, negative_threshold: float = 0.3):
        # Equation 6 parameters for negatively weighted updates
        self.negative_bias = negative_bias  # B^c_n parameter
        self.negative_threshold = negative_threshold  # T^c_n parameter
    
    def update_agent_trust(self, robot: Robot, psms: List[Tuple[float, float]]) -> None:
        """Update robot/agent trust using Beta distribution updates from paper equation (5) and (6)"""
        for value, confidence in psms:
            # Paper's equation (6): Negatively weighted updates
            # ω_{j,k} = B^c_n if v_{j,k} < T^c_n, 1.0 otherwise
            if value < self.negative_threshold:
                weight = self.negative_bias
            else:
                weight = 1.0
            
            # Apply weighting to confidence for negative evidence
            weighted_confidence = weight * confidence
            
            # Paper's equation (5) with equation (6) weighting: Beta-Bernoulli conjugate update
            delta_alpha = confidence * value
            delta_beta = weighted_confidence * (1 - value)
            
            robot.update_trust(delta_alpha, delta_beta)
            
    
    def update_track_trust(self, track: Track, psms: List[Tuple[float, float]]) -> None:
        """Update track trust using Beta distribution updates from paper equation (5) and (6)"""
        for value, confidence in psms:
            # Paper's equation (6): Negatively weighted updates
            # ω_{j,k} = B^c_n if v_{j,k} < T^c_n, 1.0 otherwise
            if value < self.negative_threshold:
                weight = self.negative_bias
            else:
                weight = 1.0
            
            # Apply weighting to confidence for negative evidence
            weighted_confidence = weight * confidence
            
            # Paper's equation (5) with equation (6) weighting: Beta-Bernoulli conjugate update
            delta_alpha = confidence * value
            delta_beta = weighted_confidence * (1 - value)
            
            track.update_trust(delta_alpha, delta_beta)
        
    
    def get_expected_trust(self, alpha: float, beta: float) -> float:
        """Calculate expected value E[trust] = alpha / (alpha + beta)"""
        return alpha / (alpha + beta)
    
    def get_trust_variance(self, alpha: float, beta: float) -> float:
        """Calculate variance V[trust] = (alpha * beta) / ((alpha + beta)^2 * (alpha + beta + 1))"""
        denominator = (alpha + beta) ** 2 * (alpha + beta + 1)
        return (alpha * beta) / denominator

class PaperTrustAlgorithm:
    """Implementation of the original paper's trust-based sensor fusion algorithm"""
    
    def __init__(self, negative_bias: float = 3.0, negative_threshold: float = 0.3):
        self.trust_estimator = TrustEstimator(negative_bias, negative_threshold)

    def update_trust(self, robots: List[Robot], environment = None) -> Dict[int, Dict]:
        """Update trust values by checking each ego robot's own reported tracks against
        what proximal robots independently observed."""

        trust_updates = {}

        # Store PSMs for each robot to be applied later
        robot_psms = {robot.id: [] for robot in robots}
        all_track_psms = {}

        # OUTER LOOP: For each ego robot, walk ITS OWN reported tracks and check whether
        # proximal robots corroborate each one
        for ego_robot in robots:
            if not ego_robot.reported_tracks:
                continue

            # Filter proximal robots by distance if environment is available
            if environment:
                proximal_robots_in_range = environment.get_proximal_robots(ego_robot)
            else:
                # Fallback: consider all other robots as proximal
                proximal_robots_in_range = [r for r in robots if r.id != ego_robot.id]

            if not proximal_robots_in_range:
                continue

            # Group proximal robots' reported tracks by object ID (a proximal robot may
            # report several objects; we need to look them up by object_id below).
            proximal_reports_by_object: Dict[str, List[Tuple[Robot, Track]]] = {}
            for proximal_robot in proximal_robots_in_range:
                for track in proximal_robot.get_reported_tracks_list():
                    proximal_reports_by_object.setdefault(track.object_id, []).append(
                        (proximal_robot, track))

            # Generate PSMs by checking each of ego's own tracks against proximal reports
            self._generate_psms_from_ego_tracks(
                ego_robot, proximal_robots_in_range, proximal_reports_by_object,
                robot_psms, all_track_psms)

        # Apply collected PSMs to update robot trust
        for robot in robots:
            if robot_psms[robot.id]:
                self.trust_estimator.update_agent_trust(robot, robot_psms[robot.id])
            
            # NEW ARCHITECTURE: Update track trust and forward to all_tracks
            track_updates_count = 0
            for track in robot.get_reported_tracks_list():
                if track.track_id in all_track_psms:
                    # Get trust deltas before update
                    old_alpha = track.trust_alpha
                    old_beta = track.trust_beta

                    # Update the reported track
                    self.trust_estimator.update_track_trust(track, all_track_psms[track.track_id])

                    # Forward to all_tracks (persistent storage)
                    delta_alpha = track.trust_alpha - old_alpha
                    delta_beta = track.trust_beta - old_beta
                    robot.forward_trust_update_to_all_tracks(
                        object_id=track.object_id,
                        delta_alpha=delta_alpha,
                        delta_beta=delta_beta
                    )
                    track_updates_count += 1
            # Debug: show how many tracks were updated
            # if track_updates_count > 0:
            #     print(f"  Robot {robot.id}: updated trust for {track_updates_count} tracks")
            
            # ALWAYS include ALL robots in trust_updates to maintain continuous trust evolution
            trust_updates[robot.id] = {
                'alpha': robot.trust_alpha,
                'beta': robot.trust_beta,
                'mean_trust': robot.trust_value,
                'num_agent_psms': len(robot_psms[robot.id]),
                'track_trust_info': {
                    track.track_id: {
                        'alpha': track.trust_alpha,
                        'beta': track.trust_beta,
                        'mean_trust': track.trust_value,
                        'num_psms': len(all_track_psms.get(track.track_id, [])),
                        'object_id': track.object_id
                    }
                    for track in robot.get_reported_tracks_list()
                }
            }
        
        return trust_updates
    
    def _generate_psms_from_ego_tracks(self, ego_robot: Robot,
                                       proximal_robots_in_range: List[Robot],
                                       proximal_reports_by_object: Dict[str, List[Tuple[Robot, Track]]],
                                       robot_psms: Dict, all_track_psms: Dict):
        """
        Generate PSMs by walking ego robot's OWN reported tracks and checking whether
        proximal robots corroborate each one - rather than walking proximal objects (which
        let an adversarial proximal robot's fabricated object penalize every innocent
        neighbor that correctly never reported it, since those neighbors have no track for
        it at all here and are simply never visited).

        For each of ego's own tracks:
        - MATCH: >=1 proximal robot also reports this object_id -> positive evidence,
          referenced against the (agent-trust-weighted) fusion of those proximal robots'
          own track trust for this object, not ego's own track trust.
        - NO MATCH: no proximal robot reports this object_id, but >=1 proximal robot has
          it within their own FoV (so they could have corroborated but didn't) -> negative
          evidence, referenced against ego's own track trust (inverted).
        """
        for obj_id, ego_track in ego_robot.reported_tracks.items():
            reports = proximal_reports_by_object.get(obj_id)

            if reports:
                # MATCH: proximal robot(s) also report this object - positive evidence for ego
                fused_expected_trust, fused_variance = self._fuse_proximal_track_trust(reports)
                avg_proximal_agent_trust = sum(r.trust_value for r, _ in reports) / len(reports)
                self._generate_positive_psm(
                    ego_robot, ego_track, fused_expected_trust, fused_variance,
                    avg_proximal_agent_trust, robot_psms, all_track_psms
                )
            else:
                # Check which proximal robots could have seen this object but didn't report it
                seeing_robots = [r for r in proximal_robots_in_range if r.is_in_fov(ego_track.position)]
                if seeing_robots:
                    # NO MATCH: proximal robot(s) could see it but none corroborated - negative
                    # evidence for ego, referenced against ego's own claimed track trust
                    avg_seeing_agent_trust = sum(r.trust_value for r in seeing_robots) / len(seeing_robots)
                    self._generate_negative_psm(
                        ego_robot, ego_track, avg_seeing_agent_trust, robot_psms, all_track_psms
                    )

    def _fuse_proximal_track_trust(self, reports: List[Tuple[Robot, Track]]) -> Tuple[float, float]:
        """
        Agent-trust-weighted fusion of multiple proximal robots' track trust for the same
        object: E[fused] = sum(agent_trust * E[track_trust]) / sum(agent_trust), and
        similarly for the variance. Falls back to an unweighted average if every reporting
        robot currently has zero agent trust weight.
        """
        weights = []
        expected_trusts = []
        variances = []
        for robot, track in reports:
            weights.append(robot.trust_value)
            expected_trusts.append(self.trust_estimator.get_expected_trust(
                track.trust_alpha, track.trust_beta))
            variances.append(self.trust_estimator.get_trust_variance(
                track.trust_alpha, track.trust_beta))

        total_weight = sum(weights)
        if total_weight > 0:
            fused_expected_trust = sum(w * e for w, e in zip(weights, expected_trusts)) / total_weight
            fused_variance = sum(w * v for w, v in zip(weights, variances)) / total_weight
        else:
            fused_expected_trust = sum(expected_trusts) / len(expected_trusts)
            fused_variance = sum(variances) / len(variances)

        return fused_expected_trust, fused_variance

    def _generate_positive_psm(self, ego_robot: Robot, ego_track: Track,
                               fused_expected_trust: float, fused_variance: float,
                               avg_proximal_agent_trust: float,
                               robot_psms: Dict, all_track_psms: Dict):
        """
        Generate positive PSM for ego_robot when proximal neighbor(s) also report the same
        object ego reported.

        Agent PSM: value = E[fused proximal track trust], confidence = 1 - V[fused proximal
        track trust]. Using the PROXIMAL robots' own assessment of the object (not ego's own
        claimed track trust) as evidence for ego's agent trust avoids the circularity of a
        robot's trust being justified by its own self-reported confidence.

        Track PSM (for ego's own track): value = 1 (match), confidence = average agent trust
        of the proximal robots that corroborated it.
        """
        # Agent PSM (for ego_robot): value = E[fused_track_trust], confidence = 1-V[fused_track_trust]
        agent_value = fused_expected_trust
        agent_confidence = 1.0 - fused_variance
        robot_psms[ego_robot.id].append((agent_value, agent_confidence))

        # Track PSM (for ego's own track): value = 1 (match), confidence = avg proximal agent trust
        track_value = 1.0
        track_confidence = avg_proximal_agent_trust

        if ego_track.track_id not in all_track_psms:
            all_track_psms[ego_track.track_id] = []
        all_track_psms[ego_track.track_id].append((track_value, track_confidence))

    def _generate_negative_psm(self, ego_robot: Robot, ego_track: Track,
                               avg_seeing_agent_trust: float,
                               robot_psms: Dict, all_track_psms: Dict):
        """
        Generate negative PSM for ego_robot when proximal neighbor(s) could see the object
        ego reported (it's within their FoV) but none of them corroborated it.

        Agent PSM: value = E[ego_track_trust], confidence = 1 - V[ego_track_trust]. Ego's own
        claimed track trust is the reference here (there is no proximal track to fuse - by
        definition nobody else reported this object). NOT inverted: update_agent_trust already
        treats a low value as negative evidence (delta_beta dominates when value is small), so
        as ego's own uncorroborated track trust is driven down over time by the track-level PSM
        below, that same low value correctly pulls ego's agent trust down too - inverting it
        here would flip a low, correctly-suspicious track trust into a high agent_value, which
        update_agent_trust reads as strong positive evidence (the opposite of what's intended).

        Track PSM (for ego's own track): value = 0 (uncorroborated), confidence = average
        agent trust of the proximal robots that could have seen it but didn't report it.
        """
        ego_track_expected_trust = self.trust_estimator.get_expected_trust(
            ego_track.trust_alpha, ego_track.trust_beta)
        ego_track_trust_variance = self.trust_estimator.get_trust_variance(
            ego_track.trust_alpha, ego_track.trust_beta)

        # Agent PSM (for ego_robot): value = E[ego_track_trust], confidence = 1-V[ego_track_trust]
        agent_value = ego_track_expected_trust
        agent_confidence = 1.0 - ego_track_trust_variance
        robot_psms[ego_robot.id].append((agent_value, agent_confidence))

        # Track PSM (for ego's own track): value = 0 (uncorroborated), confidence = avg
        # agent trust of proximal robots that could see it but didn't report it
        track_value = 0.0
        track_confidence = avg_seeing_agent_trust

        if ego_track.track_id not in all_track_psms:
            all_track_psms[ego_track.track_id] = []
        all_track_psms[ego_track.track_id].append((track_value, track_confidence))
    
    def get_expected_trust(self, alpha: float, beta: float) -> float:
        """Calculate expected value E[trust] = alpha / (alpha + beta)"""
        return self.trust_estimator.get_expected_trust(alpha, beta)
    
    def get_trust_variance(self, alpha: float, beta: float) -> float:
        """Calculate variance of trust distribution"""
        return self.trust_estimator.get_trust_variance(alpha, beta)